### ISSUE TITLE
BufferedInputStream

### ISSUE THREAD

**Issue by pirateprogrammer** [Mentolity/CSE2102#4]
Implementing the bufferedInputStream again (implemented in Music.java and Effect.java) gives me an I/O error. Besides that, no other issues (I tested my code to make sure that it was fine before uploading to the master branch).

java.io.IOException: Stream closed
	at java.io.BufferedInputStream.getInIfOpen(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at com.sun.media.sound.RIFFReader.read(Unknown Source)
	at com.sun.media.sound.RIFFReader.<init>(Unknown Source)
	at com.sun.media.sound.WaveFloatFileReader.internal_getAudioFileFormat(Unknown Source)
	at com.sun.media.sound.WaveFloatFileReader.getAudioFileFormat(Unknown Source)
	at com.sun.media.sound.WaveFloatFileReader.getAudioInputStream(Unknown Source)
	at javax.sound.sampled.AudioSystem.getAudioInputStream(Unknown Source)
	at game.Effect.run(Effect.java:31)

**Comment by Mentolity** [comment]
You had the paths wrong. Use "/filename.xyz" not "./res/filename.xyz" 
Also you were missing an extra ")"
